- .github/workflows/documentation-links.yaml
- .readthedocs.yaml
- docs/.gitignore
- docs/Makefile
- docs/conf.py
- docs/garden_ai.rst
- docs/index.rst
- docs/make.bat
- docs/modules.rst
- examples/basic_example.py
- garden_ai/garden.py
- poetry.lock
- pyproject.toml
- tests/test_garden.py
Users of the GardenClient need to obtain valid GlobusAuth tokens in order to access the service.
Solution to #3 
1. Added Globus-SDK to project.
2. Used NativeAppAuthorizer to launch an OAuth3 flow to obtain a token.
3. Use the JSON TokenStore to save tokens.
4. Created unit tests to exercise the auth workflow
This story includes setting up Sphinx documentation and publishing to readthedocs.
Notes:
There is a [ridiculous pin in flake8 on an old version of importlib-metadata](https://github.com/PyCQA/flake8/pull/1438) which is incompatible with Sphinx. I had hoped to put sphinx tooling in `pyroject.yaml`, but it meant pinning to a very old version of flake8. In the end I kept flake8 and removed the sphinx libraries.
> Add Authentication to Garden Client

- garden_ai/steps.py
- garden_ai/utils.py
- poetry.lock
- pyproject.toml
- tests/test_models.py
this was a fun one -- closes #54, closes #32, closes #28 and obsoletes #35 thanks to the **very** thorough efforts of `beartype`: https://github.com/beartype/beartype#features. 
First class support for scientific-community-motivated 3rd party type hints like `numpy.typing` or typed PyTorch tensors also looks great. 
Incidentally, the beartype readme is also (if you don't mind their puns) imo the best resource I've stumbled across for making sense of the wide world of type-hint-PEPs (check out the "compliance" section)
----
:books: Documentation preview :books:: https://garden-ai--62.org.readthedocs.build/en/62/
> 54 outsource issubtype

- garden_ai/app/main.py
- garden_ai/app/model.py
- tests/test_cli.py
- tests/test_models.py
Builds on #68. Closes #38.
Adds a `garden model register` command that allows users to upload a model from the CLI.
- The backend is currently set up such that the client interacts with S3 directly. So only users who can read/write directly to the artifact bucket can use this. (So basically, only usable by Garden developers at the moment.)
----
:books: Documentation preview :books:: https://garden-ai--70.org.readthedocs.build/en/70/
> Upload model from CLI

- .github/PULL_REQUEST_TEMPLATE.md
Look at this unstructured free text. Am I forgetting important information? What if we had a lightweight PR template that gave a little helpful nudge to PR writers but wasn't too opinionated? That would really be something.
----
:books: Documentation preview :books:: https://garden-ai--76.org.readthedocs.build/en/76/
> Make a PR template

- .github/workflows/ci.yaml
- garden_ai/client.py
- garden_ai/mlflow_bandaid/binary_header_provider.py
- garden_ai/templates/pipeline
- poetry.lock
- pyproject.toml
- tests/integrations/test_mlflow.py
Resolves [#11](https://github.com/Garden-AI/garden-backend/issues/11). Sibling PR with https://github.com/Garden-AI/garden-backend/pull/12
Adds Content-Type HTTP header with value "application/octet-stream" to all outbound requests generated by the MLFlow client. This enables us to specify in AWS API Gateway that we do not want to coerce payloads with that header to text.
This adds code that accesses a protected attribute of the MLFlow library, which is bad. For what it's worth, the `RequestHeaderProvider` registry is intended as an extension point. MLFlow would just prefer you create a new package to do so. I'd like to avoid making a new package or packaging a short-lived fork of MLFlow to unblock us. I think this quick-and-somewhat-dirty fix is a good expedient while we pursue a proper …
> Add content-type header to all outbound calls from MLFlow client

- docs/quickstart.rst
[Fixes #81](https://github.com/Garden-AI/garden/issues/81) 
Minor fix to quickstart docs. The prefix ```garden-ai``` was absent from the CLI commands. Changed only in the quickstart docs, the prefix does exist appropriately when referenced in [test_mlflow.py](https://github.com/Garden-AI/garden/blob/main/tests/integrations/test_mlflow.py) and [client.py](https://github.com/Garden-AI/garden/blob/main/garden_ai/client.py).
A simple fix that was discussed was with @WillEngler and @OwenPriceSkelly.
Reproducible by following the current [quickstart](https://github.com/Garden-AI/garden/blob/main/docs/quickstart.rst) as written, will not create the intended help command output.
Outcome if quickstart followed in Current state:
Outcome if quickstart followed in the proposed state:
----
:books: …
> add garden-ai prefix to CLI commands in quickstart.rst

- garden_ai/app/pipeline.py
- garden_ai/mlmodel.py
- garden_ai/pipelines.py
- garden_ai/steps.py
- garden_ai/templates/pipeline
- garden_ai/utils.py
- poetry.lock
- pyproject.toml
- tests/conftest.py
- tests/test_models.py
- tests/test_utils.py
Addresses #65, aiming at a smooth hand off to #39 
This PR adds the following behavior to the initialization of pipeline/step objects:
steps now extract model-specific dependencies from any models referenced in a default argument, e.g. `@step`-decorated function like `def my_step(*arg, model=garden_ai.Model('...')): pass` will have recorded the dependencies listed in the mlflow model's conda.yml in `my_step.model_conda_dependencies` and/or `my_step.pip_dependencies`, per the `conda.yml`. Steps also track the python version for the model in `my_step.python_version`, if one is specified by the requirements file for the model.
pipelines collect any of their step-level dependencies in `pipeline.conda_dependencies` and/or or `pipeline.pip_dependencies`, as appropriate. Pipelines also include …
> Unified pipeline requirements

- examples/requirements.txt
- examples/toy_example.py
- garden_ai/app/console.py
- garden_ai/app/pipeline.py
- garden_ai/client.py
- garden_ai/globus_compute/containers.py
- tests/conftest.py
- tests/integrations/test_container_build.py
- tests/test_globus_compute.py
Implements #39 
Adds a client method that we can use to build a container in the pipeline registration flow.
Added unit tests and an integration test. Also I made a little dummy cli wrapper not included in this PR to check the pretty status indicator. That code isn't in this PR, but here is what the status indicator looks like. (The dots spin around ✨)
----
:books: Documentation preview :books:: https://garden-ai--89.org.readthedocs.build/en/89/
> Add GardenClient method that builds a container with ContainerService

- garden_ai/pipelines.py
- garden_ai/templates/pipeline
small fix in anticipation of #51.
makes pipeline's requirements_file attribute optional, with a default value of `None` (from `"./requirements.txt"`)
updates the pipeline template with instructions for specifying a requirements file, including important note that the path must be an absolute path (a possible future improvement could be to relax this constraint)
updates pipeline validators to handle `None` as a requirements file gracefully
Fixes issue where pipelines could not be created by the CLI due to lacking a real requirements file, despite a requirements file not being necessary yet (if at all)
This fix is not a hack; the issue just prompted the realization that this attribute should have been optional all along (was only implemented recently in #65)
using `importlib` in a repl to …
> fix: make `pipeline.requirements_file` optional

- garden_ai/mlmodel.py
- garden_ai/steps.py
- tests/conftest.py
Fixes #93 
- when we register with funcx and serialize the function object, we also serialize any objects included in the default argument list. 
- This meant that we were accidentally including the entire model implicitly (in the form of a large `mlflow.pyfunc.PyFuncModel` object) when we registered a pipeline containing it.
- Now, the object implicitly serialized (a new `garden_ai.mlmodel._Model` object) is *much* smaller because it waits to load an underlying `mlflow.pyfunc.PyFuncModel` until it's actually necessary to make a prediction -- i.e. the pipeline is actually running.
More details in #93 
Just needed to update the fixtures included earlier 
----
:books: Documentation preview :books:: https://garden-ai--95.org.readthedocs.build/en/95/
> 93 lazy download models

- garden_ai/client.py
- garden_ai/funcx_bandaid/serialization_patch.py
Temporary expedient to unblock #40
The FuncX client currently can't handle the way Garden composes functions together. (It effectively only serializes the top level function but leaves out the functions being composed.) This PR uses the idea @OwenPriceSkelly has proposed to the FuncX team as a proper fix.
Hopefully this will be around for a month tops until the fix gets into FuncX.
I tested this on Owen's WIP remote execution branch. Without the monkeypatch I got the telltale KeyError at execution time. (See error report in Owen's PR: https://github.com/funcx-faas/funcX/pull/1083) With the monkeypatch included we get past that error and hit our pipeline code. 
----
:books: Documentation preview :books:: https://garden-ai--103.org.readthedocs.build/en/103/
> Monkeypatch FuncX client to get around clientside serialization bug

- garden_ai/app/garden.py
- garden_ai/app/pipeline.py
- garden_ai/client.py
- garden_ai/gardens.py
- garden_ai/globus_compute/remote_functions.py
- garden_ai/local_data.py
- garden_ai/pipelines.py
- garden_ai/steps.py
- garden_ai/utils/misc.py
- tests/conftest.py
- tests/fixtures/database_dumps/one_pipeline_one_garden_connected.txt
- tests/fixtures/database_dumps/one_pipeline_one_garden_unconnected.txt
- tests/fixtures/fixture_pipeline/integration_pipeline.py
- tests/test_cli.py
- tests/test_local_db.py
- tests/test_models.py
Closes #113 
This PR introduces the `RegisteredPipeline` class, which is strictly metadata so that it can be de-/serialized without losing anything. 
This PR also changes the `Garden` class so that it only has a list of `pipeline_ids`, rather than full pipeline objects -- to access more than just the uuid of a garden's pipeline, the class now has a few helpers like `garden.collect_pipelines()` and `.expanded_metadata()`. 
All the database helper functions that previously returned a dictionary now return an object 
See also the description of #113 
How did you test this? 
Painstakingly 
----
:books: Documentation preview :books:: https://garden-ai--115.org.readthedocs.build/en/115/
> `RegisteredPipeline` class

- .github/workflows/ci.yaml
- garden_ai/__init__.py
- garden_ai/__main__.py
- garden_ai/client.py
- garden_ai/local_data.py
- garden_ai/pipelines.py
- poetry.lock
- pyproject.toml
- tests/conftest.py
- tests/fixtures/fixture_pipeline/env_vars_pipeline.py
- tests/fixtures/fixture_pipeline/soup_pipeline.py
- tests/integrations/test_pipeline_registration.py
Closes #102 
- Fixes(?) code coverage 
- Remote execution via a `RegisteredPipeline`, when instantiated like `remote_pipeline = client.get_registered_pipeline(doi_or_uuid)`, will set the necessary env variables for the endpoint-side model download.
- `RegisteredPipeline`'s are callable, just like local ones, but also accept a `_env_vars` kwarg, e.g. `remote_pipeline(input_data, another_arg, _env_vars={"ENV_VAR":"ENV_VALUE"}, ...)` 
- It also has an attribute `remote_pipeline._env_vars`, which takes precedence over the kwarg if both are set. 
I ended up including the actual functional changes with #113's earlier PR, so it won't be obvious from this diff what is actually doing the work here -- check out the `utils.misc.inject_env_kwarg` helper and the tweak to how we register the pipeline …
> remote pipelines can set env vars

- garden_ai/gardens.py
- garden_ai/mlmodel.py
- garden_ai/pipelines.py
- garden_ai/steps.py
- tests/cli/test_garden.py
- tests/fixtures/database_dumps/one_pipeline_one_garden_connected.txt
- tests/fixtures/database_dumps/one_pipeline_one_garden_unconnected.txt
- tests/test_models.py
Closes #97
This PR creates a link from Pipelines to Models via a new `model_uris` field in Pipelines and Steps. It populates those fields at Pipeline init time. And the model metadata gets persisted by enriching Pipeline models at search ingest time, taking Pipelines' references to models and fleshing them out with a full Model metadata object.
Added or expanded unit tests to make sure I covered:
- At `garden publish` time, model metadata is included in the expanded garden metadata. (Gardens include full pipelines as children and pipelines include full models as children.)
- model_uris get added to pipelines at pipeline init time as part of the same process where we pull step requirements into pipeline requirements.
----
:books: Documentation preview :books:: …
> Persist model metadata to Globus Search

- .github/workflows/ci.yaml
- garden_ai/__init__.py
- garden_ai/_version.py
- garden_ai/app/main.py
- garden_ai/pipelines.py
- garden_ai/version.py
- pyproject.toml
- tests/test_models.py
fixes #63 
- We now have a package-level `garden_ai.__version__` 
- We use this in the cli to implement a `--version` flag
- we also use this to pin the correct version of the sdk as a pipeline dependency 
The version in `pyproject.toml` has been changed to '0.0.0' so that we know to ignore it. In our case, the actual `__version__` (inferred by `importlib.metadata.version`) depends on the kind of install; git-based installs (e.g. the kind `poetry install` or `pip install -e /path/to/garden/repo`) would do) would still think the version is `0.0.0`. anything that's been released to pypi (e.g. `{pip, pipx} install garden-ai` will know the actual version it was installed as. 
added a test and went through the motions myself with the cli -- since I couldn't have verified that the "release …
> 63 version fixes

- docs/developer_guide/contributing.md
- poetry.lock
- pyproject.toml
also removes sphinx as a dependency
This should have been included as part of #136
----
:books: Documentation preview :books:: https://garden-ai--145.org.readthedocs.build/en/145/
> add a brief writing-documentation section to contributor guide 

- garden_ai/app/garden.py
- tests/cli/test_garden.py
Fixes #141 
Adds print of DOI on garden create. If no DOI exists, prints UUID.
Added unit test to check if DOI is being printed to stdout on garden create
----
:books: Documentation preview :books:: https://garden-ai--146.org.readthedocs.build/en/146/
> garden create DOI print fix (#141)

- garden_ai/steps.py
- tests/test_models.py
Completes #144 
This adds a `source` field to steps, containing the snippet of source code users wrote defining the underlying function. This means that builtins and some other functions can't be used as steps, but they can still be easily used within steps, even if they're only one line. Also, we apparently already made it impossible to use builtins because they wouldn't have had annotations we could use -- I couldn't come up with any steps that would be invalid now but valid before this, anyway. 
```python
@step
def preprocessing(input_data: pd.DataFrame) -> pd.DataFrame:
"""doing some preprocessing"""
smiles = input_data["smiles"]
return smiles
assert preprocessing.source == '@step\ndef preprocessing(input_data: pd.DataFrame) -> pd.DataFrame:\n    """doing some preprocessing"""\n …
```
> 144 steps copy source code

- garden_ai/client.py
- garden_ai/mlmodel.py
Fixes #78 
Prevents users from needing to manually re-authorize by refreshing tokens as necessary before they are used. This is accomplished by ensuring they are valid before returning them in the new get method.
A quick run-through of the codebase revealed no further usages of the `client.garden_authorizer.access_token`, but any current and future uses of this property should instead be replaced with the new get method `_get_garden_access_token()`.
This is a rather annoying problem to test, however, it could be done by simply waiting on an old token.
----
:books: Documentation preview :books:: https://garden-ai--149.org.readthedocs.build/en/149/
> add naive approach to token refresh

- docs/architecture_overview.md
- garden_ai/pipelines.py
- garden_ai/utils/misc.py
- tests/conftest.py
- tests/test_models.py
- tests/test_utils.py
fixes #135 
Previously, there had been several places we collected dependencies that would eventually become part of the container spec:
1. from a model, whether implicitly via mlflow or explicitly via the CLI
2. from a step, whether explicitly by setting the attribute(s) or inferred from some model it uses (see 1)
3. the pipeline itself, explicitly via the attribute(s), explicitly via a requirements file, or implicitly from a step (see 2)
Now the only dependencies that the pipeline keeps are those explicitly set via the respective attributes or (typically) via a requirements file. 
Step- and model-level dependencies are still collected for the sake of warning users when there's a mismatch, but they don't have any effect on the actual packages requested in the container. 
Updated old …
> 135 fix dependency conflict

- garden_ai/client.py
- garden_ai/globus_search/garden_search.py
`Fixes #152`
Move the request to Globus to the garden-backend so users do not need authorization.
[The corresponding update to the garden-backend](https://github.com/Garden-AI/garden-backend/pull/22).
Currently untested. Needs corresponding update to the garden-backend.
----
:books: Documentation preview :books:: https://garden-ai--177.org.readthedocs.build/en/177/
> Outsource publish request to garden-backend

- .github/workflows/ci.yaml
- garden_ai/client.py
- garden_ai/constants.py
- garden_ai/globus_compute/login_manager.py
- tests/conftest.py
- tests/test_client.py
Part of (#153)
Currently when initializing a GardenClient, it always requires refresh tokens. However, if we want to initialize with a Client Credentials Grant, rather than the regular Authorization Code Grant, we won't have a refresh token.
Changed GardenClient __init__ to also accept auth_client of type ConfidentialAppAuthClient to initialize with a Client Credentials Grant.
Added github secrets GARDEN_API_CLIENT_ID and GARDEN_API_CLIENT_SECRET to github action env vars.
In order to do end-to-end testing, we needed a Client Credentials Grant since the Authorization Code Grant requires the user to manually login.
Added unit test for GardenClient init with Client Credentials Grant.
No documentation added.
----
:books: Documentation preview :books:: …
> Initializing a GardenClient with a Client Credentials Grant

- garden_ai/client.py
- garden_ai/globus_search/garden_search.py
Add auth header to publish garden request so that it doesn't 401 Unauthorized.
The request was sent through local deployment of the SDK and returned successfully.
----
:books: Documentation preview :books:: https://garden-ai--179.org.readthedocs.build/en/179/
> add auth header to outbound request

- garden_ai/app/garden.py
I noticed that the error the CLI catches when publishing is no longer something that the publishing function would ever raise, so I simply switched which exception it catches to the correct one.
----
:books: Documentation preview :books:: https://garden-ai--180.org.readthedocs.build/en/180/
> Fix cli error catching

- garden_ai/model_file_transfer/upload.py
- tests/test_mlmodel.py
Fixes a bug that caused model uploading to fail due to a path suffix being appended in two places.
I ran an end-to-end test that went all the way through with no errors.
----
:books: Documentation preview :books:: https://garden-ai--192.org.readthedocs.build/en/192/
> remove extra "model.zip" during upload

- garden_ai/constants.py
- garden_ai/pipelines.py
Fixes #161 
Instead of a "Value Error" if no endpoint is specified for remote execution of the pipeline, it instead uses the DLHub default compute endpoint.
If there is not a specific endpoint that you want to use, it is no longer necessary to specify one.
I tested it by creating my own pipelines and Garden and testing through both Jupyter notebook and the command line interface to see if I would get an error if no endpoint was specified.
I do not think it is necessary. In pipelines.py, the description has been updated on what the endpoint variable is to run the registered pipeline remotely.
----
:books: Documentation preview :books:: https://garden-ai--196.org.readthedocs.build/en/196/
> 161 changes for DLHub endpoint if not user specified

- garden_ai/utils/_meta.py
forgot to populate `short_name` in #190 when loading a pipeline from user's `pipeline.py` 
----
:books: Documentation preview :books:: https://garden-ai--207.org.readthedocs.build/en/207/
> fix: ensure short_name is not None when registering pipeline

- garden_ai/client.py
`Fixes #205 `
Fixes #205 by generating presigned URLs at garden publish time.
I implemented this change locally, and observed success in an end-to-end test.
----
:books: Documentation preview :books:: https://garden-ai--214.org.readthedocs.build/en/214/
> generate presigned_urls at publish time

- .github/workflows/ete_test_full.yml
- .github/workflows/ete_test_skinny.yml
PR #235 broke the get-latest-tag action in the end to end test workflow. Fixes set output for get-latest-tag action.
----
:books: Documentation preview :books:: https://garden-ai--238.org.readthedocs.build/en/238/
> End to end test latest-tag output fix

- garden_ai/app/pipeline.py
- garden_ai/client.py
- garden_ai/local_data.py
- garden_ai/utils/misc.py
- tests/conftest.py
- tests/test_local_db.py
`Fixes #217`
Adds caching to the container building process. Will work for pipelines sharing a DOI and all dependencies.
Is this actually usable behavior? Does the content of the container not also depend on the content of the pipeline itself? If it doesn't (just needs uuid or otherwise), fantastic, but if it does, this may not be a usable feature except in very specific cases.
I ran from scratch several builds locally, and the caching worked as expected.
There is additionally a change in the return type of `client.register_pipeline`, just for fun. I'll fix what breaks in relation to that.
----
:books: Documentation preview :books:: https://garden-ai--236.org.readthedocs.build/en/236/
> Container caching

- garden_ai/_model.py
- tests/test_mlmodel.py
Link to any related issues, companion PRs, or blockers. eg, `Fixes #37`
https://github.com/Garden-AI/garden/issues/222
A user is able to access the loaded model from S3 by calling model.model.
Any additional context that you think is important for reviewers or future users/contributors looking at this PR.
The issue originated from issue #200. Currently cannot replicate loading the model locally due to issues in dependencies with the required pyyaml version of ml-mast and cython.
https://github.com/yaml/pyyaml/issues/724
https://github.com/yaml/pyyaml/issues/728
Testing it through a pipeline as well as by trying to create a _Model object through the Model function and a registered model's name. In testing just obtaining the model, you need to obtain a presigned_url_response with …
> #222 Load Model Without Predict

- garden_ai/utils/_meta.py
- tests/conftest.py
- tests/fixtures/fixture_pipeline/pipeline.py
- tests/test_utils.py
fixes #230 
When a pipeline is loaded from a user's `pipeline.py` module, their code is no longer "__main__ified" -- it turns out this wasn't necessary, and giving the call to `exec` an empty dict for `globals` works just as well as passing the top-level `__main__.__dict__`. 
I'm pretty sure that this was never necessary -- I originally did it like this because I wanted to guarantee that the user's top level `import garden_ai` line would be a noop, since that's what screwed up our earlier off-the-shelf `importlib` approach, but it turns out that was overkill. 
Added a cute little unit test, but I'd made this change locally while working on the BraggNN seedling (I only discovered it trying to make a repro script for #224) and in doing so tested it pretty thoroughly. 
Updated comments but …
> fix: pipeline load util doesn't need to mainify

- docs/user_guide/installation.md
- garden_ai/app/completion.py
- garden_ai/app/garden.py
- garden_ai/app/model.py
- garden_ai/app/pipeline.py
- tests/test_completion.py
Link to any related issues, companion PRs, or blockers. eg, `Fixes #37`
https://github.com/Garden-AI/garden/issues/164
When a user wants to reference a garden, pipeline, or model, in hitting the key [TAB][TAB] twice in the CLI shows a list of potential options they can select from. 
Here are some possible options:
- garden-ai model show [TAB][TAB]
- garden-ai model add-dataset --model [TAB][TAB]
- garden-ai pipeline show [TAB][TAB]
- garden-ai pipeline add-repository --doi [TAB][TAB]
- garden-ai pipeline add-paper --doi [TAB][TAB]
- garden-ai garden show [TAB][TAB]
- garden-ai garden add-pipeline --garden [TAB][TAB] --pipeline [TAB][TAB]
- garden-ai garden publish --garden [TAB][TAB]
Important changes a user needs to make in order to make tab completion working:
1. In your terminal, run …
> 164 cli tab completion

- .github/workflows/ete_test_full.yml
- garden_ai/_model.py
- garden_ai/mlmodel.py
- tests/conftest.py
- tests/test_mlmodel.py
Fixes #218 
Allows sklearn pipelines and preprocessors to be upload as models to Garden. 
* Redefines `__getattr__` in `_Model` to proxy all attributes of the stored `_model` to the `_Model` class. This allows users to be able to call the internal `_model` methods using their `_Model` object.
* Changes mlflow load for sklearn models from `mlflow.pyfunc.load_model` to `mlflow.sklearn.load_model`.
* Adds new metadata `garden_load_strategy` to mlflow upload.
* Adds unit tests for loading sklearn models.
----
:books: Documentation preview :books:: https://garden-ai--246.org.readthedocs.build/en/246/
> Sklearn preprocessor support 

- garden_ai/client.py
- garden_ai/utils/misc.py
- tests/test_local_db.py
Adds every parameter to the container build operation as a component of the cache tag.
I tested the cache locally and it worked.
----
:books: Documentation preview :books:: https://garden-ai--249.org.readthedocs.build/en/249/
> add all container spec vars to cache tag

- garden_ai/client.py
- garden_ai/pipelines.py
- tests/integrations/test_pipeline_registration.py
- tests/test_client.py
Closes #255
Adds a new optional field to the Pipeline object where a user can specify the UUID of a registered container in Globus Compute.
I'm not advertising this far and wide in the docs or any console messages just yet. Still thinking through how we really want to handle cases where we need custom containers, but this is a good escape hatch for now.
I added a unit test to confirm that the UUID gets passed into the function registration process as I expect. I also did some manual testing where I registered a pipeline using this parameter and confirmed that it was registered with the specified container.
I'm keeping it sneaky for now.
----
:books: Documentation preview :books:: https://garden-ai--258.org.readthedocs.build/en/258/
> Add field to Pipeline that lets user specify container uuid

- docs/Models.md
- docs/user_guide/tutorial.md
- garden_ai/app/model.py
- garden_ai/client.py
- garden_ai/mlmodel.py
- garden_ai/model_file_transfer/upload.py
- tests/cli/test_model.py
- tests/integrations/test_mlflow.py
- tests/test_mlmodel.py
Closes #232 
Adds client method that is meant to be used from a notebook context or similar to upload a model that's in memory without needing to serialize and deserialize it.
As a byproduct this breaks up the monster `stage_model_for_upload` function in mlmodel.py. The original behavior should be exactly preserved though, bar a name change.
- Updated existing tests
- Added an integration test that invokes the new client method
- Imported this branch in the context of Hyun/Eliu's notebook to test the new client method "in the wild". Successfully uploaded `willengler@uchicago.edu)torchmdnet-ethanol` model.
Added example to tutorial showing how to use from a notebook or similar context.
----
:books: Documentation preview :books:: https://garden-ai--259.org.readthedocs.build/en/259/
> Add client method to upload models from memory without serializing to disk first

- garden_ai/app/pipeline.py
Fixes #170 
Improve the local debugging workflow with a new CLI command (`pipeline debug`) that spits the user into an interactive Python interpreter with their pipeline defined in the namespace.
I tested all the versions of this command locally, and they were all successful.
----
:books: Documentation preview :books:: https://garden-ai--262.org.readthedocs.build/en/262/
> add debug command

- docs/user_guide/installation.md
- docs/user_guide/introduction.md
- docs/user_guide/serialization.md
- docs/user_guide/tutorial.md
- mkdocs.yml
Fixes #276 and #275
Just docs changes. Fixes broken links and recommends using venv instead of pipx for installation.
🤷 
Ran the docs generator locally and inspected. Clicked every link and adjusted the ones that weren't working.
Oh yeah 😎 
----
:books: Documentation preview :books:: https://garden-ai--286.org.readthedocs.build/en/286/
> Fix big docs gripes

- garden_ai/client.py
Fixes #287
Makes the Globus auth flow links clickable in notebooks and Google Colabs.
During the Globus auth flow, adds a check to see if Garden is running in a notebook and if it is, displays url as HTML with `IPython.display` instead of printing it. Also fixes Safari mangling the url as it is not printing the url anymore.
----
:books: Documentation preview :books:: https://garden-ai--290.org.readthedocs.build/en/290/
> Auth flow link fixes

- .flake8
- garden_ai/app/garden.py
- garden_ai/client.py
- garden_ai/constants.py
- garden_ai/globus_search/garden_search.py
closes #154 and its children #282 and #283. I'm leaving #284 as open but blocked until we're ready to actually switch over to production datacite 
This PR is the last of the productionizing PRs for now. It cleans up a handful `GARDEN_*` constants that weren't namespaced under the `garden_ai.constants.GardenConstants` class, which is also now responsible for reading the `GARDEN_ENV` environment variable and setting constants appropriately. 
The default behavior is still to hit the dev resources. The only way to hit prod resources from the CLI is to set `GARDEN_ENV=prod`. 
Also, it's still impossible to mint true dois programmatically (since we're leaving #284 open). For any "production seedlings" we might want to bless with a real DOI in the meantime, I think the easiest thing to do is to …
> 154 prod dev environment toggle

- garden_ai/pipelines.py
Fixes #304 
Add a `PipelineMetadata` class used for representing and enforcing the required metadata for registering pipelines.
Included in this code is a wholly commented out classmethod for generating a `RegisteredPipeline` from an instance of the new class. I wrote it, but then decided it was probably poor design to expose to the user (who would not need it for any reason I could discern). If the reviewer disagrees it can be uncommented, otherwise it will be removed before merging.
One of the changes here is to make every field of the `RegisteredPipeline` required, which breaks a substantial number of tests. This, of course, remains to be remedied.
Not sure what could go wrong with the new class, but if the structure is good then I can make a couple just to prove it works. More …
> add metadata class

- garden_ai/gardens.py
- garden_ai/local_data.py
- garden_ai/pipelines.py
- garden_ai/utils/misc.py
- tests/conftest.py
- tests/fixtures/database_dumps/one_pipeline_one_garden_connected.txt
- tests/fixtures/database_dumps/one_pipeline_one_garden_unconnected.txt
- tests/fixtures/search_results/valid_search_by_subject.json
Fixes #311 
We want to make sure that all the fields we need for RegisteredPipeline to work in practice are marked as mandatory in its Pydantic definition. The last one to clean up was container_uuid.
Per comments that Owen left on my last PR, I also took out the `garden_json_encoder`. It could be nice to go even further and replace our use of the UUID class in Pydantic fields and just use a string field with a UUID validator. Then we wouldn't have to specify the Pydantic encoder anywhere. But this is a nice little improvement for now :) 
I just relied on the unit tests for this.
Nothing big docs-wise here.
----
:books: Documentation preview :books:: https://garden-ai--315.org.readthedocs.build/en/315/
> Make container_uuid a mandatory field 

- garden_ai/app/notebook.py
- garden_ai/containers.py
Updates help text for `garden-ai notebook start` to show example use of `--base-image` and shows the user the command `garden-ai notebook list-premade-images` so they can see all the available base images.
Adds exception to `garden-ai notebook start` showing all the available base images when the user tries to reference a base image that does not exist.
----
:books: Documentation preview :books:: https://garden-ai--323.org.readthedocs.build/en/323/
> Base image error handling

- garden_ai/pipelines.py
Part 2/2 of #294
This PR adds new fields to the `RegisteredMetadata` class that will allow us to add more details about the container used in the pipeline, plus the raw text of the notebook for pipelines made with notebooks.
This just adds new fields but doesn't populate them yet. I'll follow up on that once Owen's publishing PR is in.
Again, just relied on unit tests. This just adds optional fields so not much risk here.
No docs changes yet
----
:books: Documentation preview :books:: https://garden-ai--330.org.readthedocs.build/en/330/
> Add additional fields to RegisteredPipeline

- garden_ai/__init__.py
- garden_ai/client.py
- garden_ai/pipelines.py
- garden_ai/scripts/save_session_and_metadata.py
- tests/test_models.py
Closes #334 
This PR re-introduces steps to the new publishing flow. Users can decorate functions in their notebook with `@garden_step` and that will expose the function as a step in their pipeline's metadata so that the UI can feature it. Pipeline functions (the ones with `@garden_pipeline`) are also steps by default.
For now there is no way to specify the order of your steps. The order is always the order they are defined in your notebook, with the pipeline function always the final step. If there is more than one pipeline in a notebook, all the steps apply to both pipelines. If this idea takes off we'll probably want to let users specify which apply to which, but the intention here is to cover the simple case first so we can see it working end to end and go from there.
I made some …
> Add steps to the new publishing flow with @garden_step decorator

- garden_ai/model_connectors/hugging_face.py
This is quality of life improvement that came up while working on a PyTorch seedling. (https://github.com/Garden-AI/seedlings/issues/14)
This PR makes it so that, by default, Hugging Face download paths are added to sys.path, letting users import Python modules from their Hugging Face repos. In practice this is a helpful way to share model class definition files for PyTorch.
Any additional context that you think is important for reviewers or future users/contributors looking at this PR.
I co-developed this with the torch seedling and confirmed it worked in that context: https://github.com/Garden-AI/seedlings/pull/17
No docs for this yet
----
:books: Documentation preview :books:: https://garden-ai--349.org.readthedocs.build/en/349/
> Make it more convenient to import code from Hugging Face repos

- garden_ai/base_image_dockerfiles/Dockerfile_jupyter_tf_3.10
- garden_ai/base_image_dockerfiles/Dockerfile_jupyter_tf_3.11
- garden_ai/base_image_dockerfiles/Dockerfile_jupyter_tf_3.9
Fixes #350 
This PR tweaks some Dockerfiles so that when you boot up a TensorFlow base image, you can do `import tensorflow as tf` right away.
I tested all 4 of the tensorflow base images. The 3.8 variant worked already. 3.9-3.11 didn't. I tried out the tweak in this PR and it did the trick for those 3 variants. I've already pushed up the fixed images to the `gardenai` DockerHub account.
I tested this on an EC2 ubuntu workstation. I tested all 3 variants and ran a simple test notebook on top of them.
No docs changes.
----
:books: Documentation preview :books:: https://garden-ai--352.org.readthedocs.build/en/352/
> Fix TensorFlow base images

- .safety-policy.yml
- garden_ai/app/notebook.py
- garden_ai/backend_client.py
- garden_ai/client.py
- garden_ai/pipelines.py
- garden_ai/utils/notebooks.py
- tests/test_utils.py
This is the SDK/CLI portion of #345 
This PR uses the new POST /notebook endpoint to upload the contents of the user's notebook to S3 and attach a public URL to a new `notebook_url` field on the pipeline metadata.
This PR is pretty by the book, but one interesting part is how we treat outputs in notebooks. For both uploading and downloading notebooks, we want to try and keep the file size sane. The most likely way that notebook file size gets out of control is `outputs`. So now we nondestructively clear the user's outputs by default before uploading. If the user has some visualization or output they really want to show, they can provide the --keep-outputs flag.
I added new unit tests for the notebook helpers. I also tested this end to end against the backend dev instance and confirmed …
> Attach notebook URL to metadata instead of full notebook contents

- garden_ai/app/notebook.py
- garden_ai/constants.py
- garden_ai/notebook_templates/empty.ipynb
- garden_ai/notebook_templates/sklearn.ipynb
- garden_ai/notebook_templates/tensorflow.ipynb
- garden_ai/notebook_templates/torch.ipynb
- garden_ai/utils/notebooks.py
Closes #360
This PR adds a bunch of improvements to `notebook start`:
- You'll get a templated notebook that matches the base image you picked. (eg, picking 3.10-torch means you get a templated notebook that uses torch.)
- You don't have to specify a notebook name if you're starting a new notebook. We will generate a random botanically inspired default name for the notebook.
- Wait a beat after spinning up the container so that when we redirect to the user's browser, they don't get a 404.
- More intuitive behavior for the `--base-image` flag. If you mistype we don't try to pull an image that doesn't exist, we abort and tell you the valid names.
- Before pulling and starting the image or making a new notebook file, we tell the user what we're about to do and let them accept or deny it.
- …
> UX Improvements to `notebook start` command

- garden_ai/__init__.py
- garden_ai/app/notebook.py
- garden_ai/entrypoints.py
- garden_ai/scripts/save_session_and_metadata.py
Closes #342 
Inside a notebook, you can tag a function that tests an entrypoint like this:
```
@entrypoint_test(classify_irises)
def test_the_classifier():
example_input = [[5.1, 3.5, 1.4, 0.2]]
result = classify_irises(example_input)
return result
```
And then that function's text will be available in the entrypoint's metadata object in the `test_functions` list. This will let us display an example of how to use the entrypoint on the UI or in an autogenerated "Try it in Colab" notebook.
I deliberately kept this first draft of this super simple. There is no validation of the test function's contents or anything like that. And this just passes along the raw text of the test function. Enough to display the example in the UI and no more.
Also I was getting some weird behavior with container …
> Add ability for publishers to tag an `@entrypoint_test`

- garden_ai/app/notebook.py
- garden_ai/containers.py
- tests/test_containers.py
closes #336, plus addresses Logan's gripe about including requirements.txt or conda environment.yml files. 
The new functionality is all in `build_image_with_dependencies`, and all of the `garden-ai notebook` commands now accept an optional `--requirements` path to either a pip- or conda-style requirements file. 
local data still only tracks the most recently selected `--base-image` instead of storing the bespoke local images generated by the new function
My first few stabs at this I had the CLI either remember the most-recently-used requirements file along with the base image and/or caching the pre-baked image instead, but it felt pretty unwieldy for not a lot of benefit; the layer caching we get for free with docker is basically just as good as caching the custom image in local data. …
> 336 pre install garden in base images

- docs/architecture_overview.md
- docs/index.md
- docs/user_guide/faqs.md
- docs/user_guide/installation.md
- docs/user_guide/tutorial.md
Some docs fixes and tweaks.
The biggest changes are:
- Remove lingering DockerHub mentions
- Mention `--requirements` and recommend it for specifying package versions.
- Move the debugging discussion to a FAQs page. Also include a tip on tensorflow with MacOS there.
I still want to take a proper crack at a second draft of the docs (#361 ) from a flow/pedagogy perspective. But this PR is just to make sure there's nothing glaringly missing/out of date for ambitious early adopters over the holidays.
N/A. I did look over the preview and make sure formatting still looked normal.
All docs
----
📚 Documentation preview 📚: https://garden-ai--374.org.readthedocs.build/en/374/
> Make some docs changes to reflect new features and fixes

- garden_ai/model_connectors/hugging_face.py
- poetry.lock
- pyproject.toml
Fixes #377 
The huggingface_hub library assumes all repos have a README.md. So the expression `ModelCard.load(repo_id)` will raise an error if README.md is not in a repo's root.
While I was messing around with dependency versions to fix a security check, I noticed that Garden's tests fail on new versions of the Globus SDK. I cut a ticket for this: https://github.com/Garden-AI/garden/issues/385 That's the reason for the new max globus-sdk version number in this PR.
I made willengler-uc/empty-model-repo to repro and test. I confirmed that on main I get the error and on my branch we don't.
n/a
----
📚 Documentation preview 📚: https://garden-ai--384.org.readthedocs.build/en/384/
> Gracefully handle a Hugging Face repo not having a README

- garden_ai/app/notebook.py
- garden_ai/containers.py
- garden_ai/entrypoints.py
- garden_ai/notebook_templates/sklearn.ipynb
- garden_ai/notebook_templates/tensorflow.ipynb
- garden_ai/notebook_templates/torch.ipynb
Closes #383 
functions decorated with `@entrypoint_test` now become no-ops at publication (and `notebook debug`) time, so users don't need to remember to comment out tests before they publish. 
`containers.build_notebook_session_image` can now set environment variables in the docker image it builds. This currently just sets a `GARDEN_SKIP_TESTS=True` flag by default, which the `entrypoint_test` decorator now checks for before calling the underlying test function.  
Just manual tests so far -- I wasn't sure how useful a unit test would be since this only changes behavior in containers, but I'm happy to add one
As a bonus though, manual testing actually turned up a lil bug in `notebook debug` (we were attempting to pull images by an id which would only exist locally) 🪲 
Updated the template …
> 383 don't run tests during publication

- garden_ai/app/console.py
- garden_ai/app/entrypoint.py
- garden_ai/app/garden.py
- garden_ai/client.py
- garden_ai/entrypoints.py
- garden_ai/gardens.py
- tests/cli/test_console.py
- tests/cli/test_entrypoint.py
- tests/cli/test_garden.py
Closes #400 
This PR adds new commands `garden-ai garden register-doi` and `garden-ai entrypoint register-doi`. These will promote the draft DOIs that Garden mints for all gardens and entrypoints to "registered" and "findable" status in Datacite.
This change is prompted by early feedback that Garden proactively creating and registering DOIs was surprising. This change makes it so that users have the option to review their work before pulling the trigger and making the DOI for an entrypoint or garden official.
The PR also adds to the `list` commands to let users easily see the draft statuses of their DOI.
_Screenshots_
As I was reviewing how we deal with DOIs, it became clear that our support for users bringing their own DOI (not one generated with our account) is broken. This PR does not …
> Let users opt in to when their DOIs are registered

- garden_ai/app/notebook.py
Owen's container handling improvements in the `docker prune` PR means there's now an extra line in build log output in the case of a build failure. The last line is something like "Removing intermediate container 33cb4f87eb1e". This PR updates some error handling code to reflect this.
Yeah, I know this is fragile ... If it breaks again let's reconsider.
Tested manually
No
----
📚 Documentation preview 📚: https://garden-ai--406.org.readthedocs.build/en/406/
> Quick fix: get correct traceback line in build errors

- .env.shared
- garden_ai/app/main.py
- garden_ai/constants.py
- poetry.lock
- pyproject.toml
fixes #284 
The default values in `garden_ai.constants` now point at prod instead of dev. This can be controlled with the environment variable `GARDEN_ENV=dev` or `GARDEN_ENV=prod`. 
So that we don't need to worry about accidentally hitting prod ourselves if that env var is left unset, I also added a `.env.shared` file at the project root which sets `GARDEN_ENV=dev`. Because this file isn't distributed to pypi, this only applies if the `garden-ai` executable was installed from source (which is always the case in e.g. a `poetry shell`). 
The `.env.shared` won't override existing values, so this works like you'd expect:  
```sh
$ (plain install) garden-ai do something                # hits prod default 
$ (poetry shell) garden-ai do something                 # hits dev default 
$ (poetry …
```
> target prod by default

- garden_ai/client.py
- garden_ai/constants.py
- garden_ai/entrypoints.py
- tests/ete/constants.py
- tests/integrations/test_pipeline_registration.py
- tests/test_entrypoints.py
This came up in the course of #402
DLHub wraps user input to models in a dictionary before sending it along to Globus Compute. Similarly, when receiving output from a successful run, DLHub unwraps the output from a nested tuple and returns the inner output to the user.
This PR makes it so that Garden will do the same for the legacy DLHub models we're migrating.
This is a little kludgey but good enough for now. We might be able to do something a little fancier where we add this code to the DLHub functions registered with Globus Compute if/when we want to get rid of this little hack.
I tested this against sample input and output I got from a DLHub model that I migrated to Garden dev. I also added new unit tests. We will still need to test this end to end in the context of the full migration …
> Add logic to format DLHub model input and output correctly

- .flake8
- .gitignore
- garden_ai/entrypoints.py
- scripts/dlhub_migrate.py
- tests/test_entrypoints.py
This PR contains much of the work for #402 
This PR has a script that creates Garden endpoints and gardens from the known-working DLHub models. After running the script you need to manually issue some CLI commands to put the endpoints in the right gardens and publish the gardens.
I also tweaked the logic that does the DLHub input/output wrapping/unwrapping after I found an issue testing end to end.
I tested this in the dev env. I confirmed the entrypoints and gardens rendered in the UI how I expected. I also did some test runs of the published entrypoints.
No docs changes.
----
📚 Documentation preview 📚: https://garden-ai--411.org.readthedocs.build/en/411/
> DLHub Migration Script

- scripts/dlhub_migrate.py
closes #408. part of #402 
This just adds `:home-run` tags to the respective image uris, so that the dlhub functions are registered against images with `home_run==0.5.0` installed and we can remove that part from the endpoint-specific worker init. 
----
📚 Documentation preview 📚: https://garden-ai--415.org.readthedocs.build/en/415/
> append `:home-run` tag to image uris

- garden_ai/containers.py
- tests/test_containers.py
Might close #414 
We _think_ that there is a bug on certain computers where stdout is not properly captured in the following line:
```
container_stdout = client.containers.run(
image=image.id,
entrypoint="/bin/sh",
command=["-c", "cat /garden/metadata.json"],
remove=True,
detach=False,
)
```
The Gardeners can't reproduce the bug, but we want to try circumventing stdout altogether to see if that fixes it. To do this we'll extract a file from the container instead of `cat`ting the file contents.
I updated the unit test and I did manual runs to confirm it still works
No
----
📚 Documentation preview 📚: https://garden-ai--416.org.readthedocs.build/en/416/
> Extract metadata.json from built container as a file instead of `cat`ting its contents

- garden_ai/model_connectors/github_conn.py
- garden_ai/utils/misc.py
- tests/test_models.py
fixes #413 
~This tweaks the `trackcalls` decorator so that `stage` can use its own `has_been_called` attribute and guarantee that it only executes once.~
This makes the GH connector behave a little more like the huggingface one by pulling instead of cloning when the directory is already a git repo. 
~Wrote a cute little unit test, since it was easy~ 
updated the unit test so it checks that pull is called instead of clone when appropriate
no docs 
----
📚 Documentation preview 📚: https://garden-ai--417.org.readthedocs.build/en/417/
> make github connector idempotent

- garden_ai/constants.py
Part of #428. Waiting to call #418 and #425 closed until I've got the helm chart cleaned up and documented etc in my other branch. 
🪦  _Here lies DLHub Endpoint. May he `CrashLoopBackOff` in eternal peace._  🪦
Thursday is upon us, and sending anything to the dlhub endpoint just gets you: 
```
globus_sdk.exc.api.GlobusAPIError: 
('POST', 'https://compute.api.globus.org/v2/submit', 'Bearer', 403, 'ENDPOINT_ACCESS_FORBIDDEN', 'Unauthorized access to endpoint 86a47061-f3d9-44f0-90dc-56ddc642c000')
```
This PR just a) changes the default endpoint to the new one and b) pours one out 🫗 for the old. 
Since only members of the associated globus group can actually use the new endpoint, the rest of #428 is going to be totally docs/error message focused to point users toward the link to join the …
> hotfix: use new endpoint uuid in `constants.py`

- garden_ai/app/garden.py
- garden_ai/backend_client.py
- garden_ai/client.py
- garden_ai/local_data.py
- garden_ai/utils/dois.py
- tests/cli/test_garden.py
Closes #421 
This PR adds a new command. `garden-ai garden delete -g 10.23677/some-doi`. It deletes the garden locally and on the search index.
By default, if a garden isn't in your data.json, the command won't let you remove it from the search index. There is a hidden `--dangerous-override` flag you can add that will let you remove it from the search index anyways.
I tested this against the new DELETE /garden-search-record endpoint in dev. I also added new unit tests for the command
Just the CLI docs for now
----
📚 Documentation preview 📚: https://garden-ai--429.org.readthedocs.build/en/429/
> `garden-ai garden delete` command

- garden_ai/app/entrypoint.py
- garden_ai/app/garden.py
- garden_ai/utils/interactive_cli.py
Closes #386
Adds new `entrypoint edit` and `garden edit` commands.
I'm deliberately making this pretty quick and dirty to avoid overbuilding this before we make an app and make this obsolete. For example, here's the view after you enter the command
You pick a field with an arrow key and enter, then click OK and you can edit the field. Having to click OK is janky, but (surprisingly) removing the need to click OK would be a step up in complexity to implement. This should solve the problem in the short term, even if it isn't beautiful.
I tested both commands manually
Just in the CLI help
----
📚 Documentation preview 📚: https://garden-ai--432.org.readthedocs.build/en/432/
> Edit entrypoint and garden metadata from the command line

- .safety-policy.yml
- garden_ai/scripts/save_session_and_metadata.py
- poetry.lock
- pyproject.toml
(hopefully) fixes #436 
This relaxes our dill constraints to exactly the same as globus compute. Because we end up installing globus compute _after_ garden anyways (in the endpoint's workerInit), I don't actually think our aggressive pinning strategy was actually _doing_ anything as of upgrading the endpoint. 
I also learned that the version we'd been pinning, dill==0.3.5.1, never supported 3.11 (oops), so I don't think it's even currently possible to publish an image running python 3.11 (dill breaks on the save_session call when I try). 
see #440 -- I'm not sure if this is going to be enough to get images running 3.11 working unless that bug really did have to do with github-related installs. Still, we don't lose any functionality we hadn't already broken by relaxing the constraint here. …
> 436 relax dill requirement

- garden_ai/client.py
- tests/test_client.py
fixes #448 
The login bug came back because (as of bumping globus compute from 2.11->2.16) we were no longer requesting a superset of the scopes that the globus compute client does. They now also need the `AuthLoginClient.scopes.manage_projects` scope, so they would trigger another login flow without it. 
Adding the same scope to our list fixed it 🎉
I cleaned up the hardcoded `COMPUTE_RESOURCE_SERVER_NAME = "funcx_service"` to reference the sdk's `ComputeScopes` constant instead, because a comment I found in their sdk indicated they might rebrand that soon too. I also noticed that we're not even requesting our own `action_all` scope (we've just been using the `test_scope`) so I added that to the list, too. 
Tested by removing my tokens and logging in again exactly once. Also need to …
> add missing `manage_projects` scope to auth code

- garden_ai/__init__.py
- garden_ai/client.py
- garden_ai/entrypoints.py
- garden_ai/mlmodel.py
closes #442 
This PR gives entrypoints a proper `datasets` field (like the existing `papers` and `repositories` fields), which users can populate with the metadata of datasets they want to showcase as related to their entrypoints. 
This keeps the existing `DatasetConnection` object mostly as-is, but I did add a validator to enforce that foundry datasets have both a url and doi. 
Once a user has instantiated `DatasetConnection` object(s) in their notebook, there are a couple ways it can be linked to an entrypoint:
- Directly via the `datasets=[...]` kwarg when instantiating their `EntrypointMetadata` object 
- via a `datasets=[...]` kwarg to the `@garden_entrypoint` decorator 
- (old way) via one of their a model connector's `connector.metadata.datasets` attribute, if they can find it. …
> add datasets to entrypoints

- .env.shared
- .pre-commit-config.yaml
- garden_ai/backend_client.py
- garden_ai/constants.py
completes #459 
what it says on the tin: this points the sdk at the appropriate `api[-dev].thegardens.ai` urls instead of the old ones. 
Two other small changes:
- kills the `@backend_toggle` decorator (RIP 🪦)
- bumps the pre-commit formatter. it was disagreeing slightly with the version of `black` that my emacs was pointed at, causing me near-fatal Minor Annoyance 
tested a few routes by using the CLI in a poetry shell against both local and dev instances, i.e. the CLI was hitting api-dev.thegardens.ai just fine. this is what prompted the backend PR to remove the trailing slashes from routes 
no docs 
----
📚 Documentation preview 📚: https://garden-ai--460.org.readthedocs.build/en/460/
> 459 point at custom domains

- garden_ai/model_connectors/exceptions.py
- garden_ai/model_connectors/github_conn.py
- poetry.lock
- tests/test_models.py
Resolves #447 
Added a method `_has_lfs_file` to the `GitHubConnector` that pulls `.gitattributes` from the remote repo and looks for any git-lfs files.
Added a check in `GitHubConnector.__init__` that raises an exception when a git-lfs file is detected. The raised exception suggests using HuggingFace to the user.
Manually tested in IPython against this [repo](https://github.com/hholb/lfs-test) with a git-lfs file.
Created a new unit test in `tests/test_models.py` to confirm the behavior.
No documentation updates. This behavior will be documented as part of #465.
----
📚 Documentation preview 📚: https://garden-ai--466.org.readthedocs.build/en/466/
> Make GitHubConnector raise exception when git-lfs files are detected

- garden_ai/client.py
- tests/test_client.py
Fixes #474
Send datacite the correctly formatted URL when registering a doi.
Added a new unit test in `test/test_client.py` to verify the URL is correct.
----
📚 Documentation preview 📚: https://garden-ai--477.org.readthedocs.build/en/477/
> Bugfix: Send correct URL to Datacite on `garden register-doi`

- garden_ai/client.py
- tests/test_client.py
Fixes: #462 
Related: https://github.com/Garden-AI/garden-backend/pull/98
To add users to the Garden Users Globus group we need to request the 'all' scope for the groups api in the auth flow.
Logged out on cli, logged back in and everything works fine.
> Change requested groups scope to 'all'

- garden_ai/backend_client.py
- garden_ai/entrypoints.py
- garden_ai/local_data.py
closes #494 
Very small PR to sanity check approach before actually replacing all of the local_data calls. This turns `import local_data` into an error in the presence of a special environment variable, and adds the basic CRUD methods to the backend client. 
There should be exactly zero behavioral difference for anyone without the `GARDEN_DISABLE_LOCAL_DATA` variable set except for one new (currently optional) `function_text` field on `RegisteredEntrypoint` for compatibility with the backend response schema. 
This is always the same as the function text otherwise stored in `.steps[0].function_text`, it's only necessary because the backend doesn't have steps.
Without the variable I can `import garden_ai` just like before, but with the environment variable set it fails with flying colors. …
> local data toggle

- garden_ai/app/entrypoint.py
- garden_ai/app/garden.py
- garden_ai/app/main.py
- garden_ai/app/notebook.py
- garden_ai/client.py
- garden_ai/gardens.py
- tests/test_local_db.py
completes #496 
This PR uses the environment variable introduced in #495 to use the new backend as a drop-in replacement anywhere that currently uses `local_data`. 
This has some ugly hacks to keep everything consistent with current behavior, especially when it comes to the `Garden` vs `PublishedGarden` distinction. Some of those `Garden` helper methods are pretty crufty and I can't wait to get rid of them completely. 
We only even have the distinction there because of constraints due to local data in the first place -- one for normalized local_data entries, the other is for the denormalized search index entries. When the migration is through and the SDK no longer needs to worry about building the entries for the search index, we can simplify down to a single normalized `GardenMetadata` …
> conditionally call local_data

- garden_ai/backend_client.py
- garden_ai/client.py
- garden_ai/globus_search/__init__.py
closes #497 
This PR includes logic to toggle the sdk's use of `/garden-search-record` routes on the backend, similar to the local_data toggle (but was _much_ simpler in practice).
The dev backend has already deprecated the `/garden-search-record` routes, which was handy for testing this. When it's time to "flip the switch" on the migration, my plan is for the SDK side to just cut a new release with the `local_data` and `globus_search._IS_DISABLED` constants hardcoded to `True`. The subsequent cleanup PR can worry about the unreachable code left over as well as tidying up the schemas we no longer need in a local-data-free world.
Manually, with `garden create`; `garden publish` and `garden delete`. Since these were the only operations that touched the search index this was enough to …
> toggle for deprecating search index routes

- garden_ai/model_connectors/model_utils.py
- garden_ai/notebook_metadata.py
- garden_ai/utils/notebooks.py
- pyproject.toml
- tests/conftest.py
- tests/model_connectors/test_github_conn.py
- tests/model_connectors/test_hugging_face.py
- tests/model_connectors/test_model_connectors.py
- tests/test_client.py
- tests/test_entrypoints.py
- tests/test_hello.py
- tests/test_notebook_metadata.py
- tests/test_utils.py
Resolves: #515 
Related: #507 
This PR add small-scale test coverage of the user-facing APIs in the SDK.
I looked through the tutorial and example notebooks to identify the primary functions and classes users will be interacting with. This PR adds test coverage of their expected behaviors from the user's perspective. All of these tests are small-scale meaning all network responses are mocked, and tests do not use docker.
The primary areas we are still lacking coverage are in the container and notebook modules. Test coverage for these modules will come in another PR.
In anticipation of adding some integration tests of the container and notebook modules, this PR adds a pytest marker: `@pytest.mark.integration` that should be added to all tests that use resources outside of the main …
> Add small-scale tests of user-facing APIs

- garden_ai/containers.py
- garden_ai/notebook_metadata.py
- poetry.lock
- tests/conftest.py
- tests/test_backend_client.py
- tests/test_containers.py
- tests/test_gardens.py
- tests/test_notebook_metadata.py
Related: #507 
This PR add small-scale test coverage of the the core modules that make garden work.
This PR includes a sizeable refactor of the `notebook_metadata.py` module to make it easier to get better test coverage. I didn't change any of the underlying logic, mostly moved stuff around into helper functions.
The tests of the containers module are mostly from the old test suite. The containers module and notebook CLI commands are where the biggest gaps in coverage are after this PR. Integration tests that cover these modules will come in another PR.
Lots of new tests, plus some old ones!
----
📚 Documentation preview 📚: https://garden-ai--530.org.readthedocs.build/en/530/
> Add small-scale tests of core modules

- garden_ai/model_connectors/model_connector.py
- tests/model_connectors/test_github_conn.py
Resolves: #521
This PR fixes a bug @WillEngler found when calling `stage` on a `GitHubConnector`.
The error was due to calling `_checkout_revision` before cloning/downloading the repo. I moved the call to `_checkout_revision` to after the download step in `stage` to ensure the repo is present before attempting to checkout the tagged revision.
Added a integration test covering the logic Will reported in #521
Run with:
`pytest -m "integration"`
----
📚 Documentation preview 📚: https://garden-ai--529.org.readthedocs.build/en/529/
> fix: staging error in GitHubConnector

- .codecov.yml
- .github/workflows/ci.yaml
- README.md
Resolves: #531 
This PR sets up a basic codecov config in `.codecov.yml` and updates the ci pipeline to use a newer version of the codecov action.
This PR adds the codecov badge to `README.md`
----
📚 Documentation preview 📚: https://garden-ai--535.org.readthedocs.build/en/535/
> Update coverage config

- garden_ai/gardens.py
- garden_ai/modal/functions.py
- garden_ai/schemas/__init__.py
- garden_ai/schemas/garden.py
- tests/conftest.py
- tests/fixtures/garden_nested_metadata_response.json
- tests/fixtures/modal_function_metadata.json
- tests/test_gardens.py
closes #537 
Follow up to #536, this gives `Garden` objects a `modal_functions` attribute as well as the ability to call those functions by name, so the interface is the same as calling normal entrypoints. 
The implementation is almost identical to the way that Garden objects look up and call their entrypoints, but note that there are a few TODOs sprinkled here and there for future PRs. 
Specific point of divergence: gardens refer to entrypoints by DOI, but we don't have DOIs for modal functions (and probably won't for a while). I decided to go with the `function_name` in lieu of a doi for now, but depending on when we get the backend side of this feature (https://github.com/Garden-AI/garden-backend/pull/165) merged it's probably easier to just use the id from the database or something. …
> gardens have ModalFunction attributes 

- docs/garden-ai.md
- garden_ai/app/garden.py
- garden_ai/client.py
- garden_ai/constants.py
- garden_ai/globus_search/garden_search.py
- tests/app/test_garden.py
- tests/conftest.py
- tests/ete/conftest.py
- tests/test_client.py
Closes #538
This PR removes the `garden-ai garden search` command and all references to the search index in the CLI. (With the exception of the search index migration script)
At first I was going to convert to the new search endpoint but ... I don't think we really need this feature in the CLI. It was one of the very first things we added to the CLI and it was largely showing that we had it hooked up to the search index. It just prints JSON. I think users can and should just use the website.
I ran `garden-ai garden` and confirmed that the `search` subcommand was gone.
I removed the command from the docs
----
📚 Documentation preview 📚: https://garden-ai--541.org.readthedocs.build/en/541/
> Remove search command and references to the search index

- garden_ai/gardens.py
- garden_ai/modal/functions.py
- garden_ai/schemas/garden.py
- garden_ai/schemas/modal.py
- garden_ai/schemas/schema_utils.py
- tests/fixtures/garden_nested_metadata_response.json
- tests/fixtures/modal_function_metadata.json
- tests/modal/test_functions.py
This is a small second pass PR which closes #540 and is basically just limited to schema tweaks on the sdk side. Nothing is functionally new vs #539. 
see also: the [corresponding backend PR](https://github.com/Garden-AI/garden-backend/pull/177) which expects the client to refer to functions by ID instead of function and app name.
~If you have this branch checked out for the sdk and `owen/post-modal-fns-uses-ids` checked out for a local instance of the backend, [this](https://gist.github.com/OwenPriceSkelly/57fa0abbddb6f63aaf4a42da205cd06a) script should reproduce the bug causing modal's containers to crash~
I decided I didn't like our custom UniqueList type throwing errors when it could just ignore repeat values and ensure the list was unique itself. This is more in line with pydantic's …
> update schemas to use function IDs

- garden_ai/gardens.py
- garden_ai/modal/functions.py
fixes #543 
This handles the bug Ben surfaced when he tried running his modal function from a notebook. 
Turns out the original strategy of just naively creating a new event loop to run the modal `_process_result` helper would break when there was already an event loop running, as is the case in jupyter/colab notebooks. 
The workaround I landed on is basically the same strategy, except it runs the new event loop in its own thread for better isolation. 
An alternative approach I eventually punted on involved trying to infer the execution context and to see if an event loop already existed to which it could submit the helper task. Punted on this because it was looking like much lower-level asyncio plumbing just for the notebook case. It felt a little silly to start up an entire new thread …
> avoid event loop conflicts calling from jupyter

- garden_ai/notebook_metadata.py
- garden_ai/scripts/save_session_and_metadata.py
- tests/test_notebook_metadata.py
Fixes #548 and friends (also fixes #520 and fixes #522)
This squashes a handful of bugs related to the metadata objects being passed around by various notebook widget helper functions. Specifically, the `NotebookMetadata` schema had every field optional, and wasn't very consistent with `None` defaults. 
To fix this family of bugs I gave the nested `RequirementsData` schema object sane defaults (`"pip"` file format and an empty list for contents) so that we could make it non-optional in the `NotebookMetadata` schema. 
Until now, we'd been representing the no-requirements case with `requirements_data=None`; now we're representing that case with empty `requirements_data=RequirementsData()` objects. This means that we no longer have to worry about occasionally accessing e.g. a nonexistent …
> bugfix empty requirements data

- garden_ai/gardens.py
- tests/test_gardens.py
Resolves: #532 
This PR defines `Garden.__getitem__` so entrypoints can be accessed like:
```
garden = client.get_garden("some-doi")
ep_func = garden["some-ep-doi"]
ep_func()
```
New unit tests
----
📚 Documentation preview 📚: https://garden-ai--550.org.readthedocs.build/en/550/
> Enable entrypoint lookups by DOI with dict-like syntax

- garden_ai/client.py
- tests/conftest.py
- tests/test_backend_client.py
- tests/test_client.py
fixes #523 
This just adds a single get_email call to the `GardenClient.__init__` method, which ensures that the client has authed with our backend at least once before attempting to pull a garden or entrypoint to run on the demo endpoint. 
This makes it so you can't accidentally try running an entrypoint before the backend has had the chance to add you to the Garden Users globus group. 
This is definitely a bit of a hack, but so is the backend's automatically adding users to the group. If there's an obvious cleaner way to do this I'm open to it, this was just the first easy fix to come to mind.
I had to tweak the garden_client fixture so the call to `BackendClient.get_user_info` would be mocked with test user data. This fixed almost all of the tests except for one backend client test, …
> add get_email call to __init__

- .safety-policy.yml
- garden_ai/backend_client.py
- garden_ai/constants.py
- garden_ai/modal/functions.py
- garden_ai/schemas/modal.py
- tests/modal/test_functions.py
Resolves: #552 
This PR updates the backend client to hit the new async modal invocation routes. The invocations are still synchronous from the user's perspective, but this allows for long-running invocations without hitting the gateway timeout for a single request to the backend.
There are no major changes in logic other than a polling loop to check the status of the invocation. There is a new environment variable "BACKEND_POLL_INTERVAL_SECONDS" to configure how often we poll for the invocation status. The default is set for 0.1 seconds, or 100ms.
We may want some sort of back-off logic in the poll interval so really long running jobs don't ping the server so much, but this probably won't be an issue until we have hundreds of invocations in-progress simultaneously. I'll leave that for an …
> Handle modal invocations asynchronously

- garden_ai/gardens.py
- garden_ai/modal/classes.py
- tests/conftest.py
- tests/fixtures/garden_nested_metadata_with_modal_class.json
- tests/fixtures/modal_class_metadata.json
- tests/test_gardens.py
Second part of #198. Closes #198
This PR accommodates Modal class methods. They come over as metadata just as normal functions do - they just have dots in their names, like "MyClass.my_method". The SDK will construct wrappers on the fly so that users can invoke class methods like my_garden.MyClass.my_method
Added a new unit test to exercise the chain of `__getattr__`s. Also did manual testing to check tab completion and HTML rendering.
Manual testing was limited as I mostly used fixture data.
Not yet, but this will definitely merit some mention in the docs
----
📚 Documentation preview 📚: https://garden-ai--554.org.readthedocs.build/en/554/
> Modal class support

- garden_ai/client.py
- garden_ai/modal/functions.py
- garden_ai/schemas/modal.py
- tests/modal/test_functions.py
fixes #564 
This PR incorporates modal's remote exception handling/display logic for invocations from garden. 
Where possible, we do this by just calling the relevant helper function from their codebase outright; where it wasn't possible to do so I plagiarized their logic as best I could. 
Here's what it looks like (modal traceback on left/proxied traceback on the right): 
The main reason we can't always just import and use modal helpers is that we can't instantiate a modal client on behalf of users who may not have modal credentials. To work around this (and clean up our `__call__` method), this PR has two new helpers (`_modal_deserialize` and `_clean_and_raise_remote_exception`) which together do essentially the same thing as the previously load-bearing …
> better modal tracebacks

- docs/user_guide/publishing/modal-publishing.md
1. Added more info on installing modal and logging into the service
2. Created section on testing and debugging your function before uploading to garden
3. Section on images along with some hints on caching model weights
----
📚 Documentation preview 📚: https://garden-ai--568.org.readthedocs.build/en/568/
> Update the Modal publish docs based on user experiance

- garden_ai/entrypoints.py
- tests/conftest.py
- tests/test_client.py
Resolves: #566 
Fixes the flakey test issues. I didn't find the root cause of the flakey backend test, so I opted to remove it. The test was not very useful (my doing), and the behavoir is covered by other tests in the suite. Removal seems to be the best option.
The test that was failing when there was no internet access was due to a bug in the fixture mocking the calls to hugging face when creating a model connector. Easy fix!
> Fix: flakey tests

- garden_ai/client.py
- garden_ai/gardens.py
- garden_ai/hpc_gardens/alpha_fold.py
- pyproject.toml
Closes https://github.com/Garden-AI/uploadathon/issues/7
This PR adds a special hidden garden. If you say `garden_client.get_garden('AlphaFold2')` you get a Garden with functions for submitting, checking on, and retrieving AlphaFold2 runs on Delta.
This is a deliberately cheeky and hacky way of getting this in to the SDK. There is no backend component and everything is hardcoded. While we are in such an experimental phase with the HPC work I think it's good to have a light touch and one clear "cutoff" point to include/exclude.
I tested this end-to-end on Delta with [this notebook](https://colab.research.google.com/drive/1BIxNq1xlWRkxGFACS8t8SxWofXYZ1HUr?usp=sharing). Unfortunately nobody but me can run this with the current Globus Compute endpoint on Delta, but we will try to change that …
> Add bespoke AlphaFold2 Garden

- .safety-policy.yml
- garden_ai/backend_client.py
- pyproject.toml
- tests/conftest.py
- tests/test_backend_client.py
Resolves: #576 
This PR disallows fetching archived gardens by raising an exception if the backend client gets a garden response with the `is_archived` field set to `True`.
New unit test
----
📚 Documentation preview 📚: https://garden-ai--578.org.readthedocs.build/en/578/
> Disallow fetching archived gardens

- poetry.lock
- pyproject.toml
SDK-side of bumping our modal dependency to 1.0 everywhere.
Fingers crossed bumping the backend is just as painless 🤞 
Sanity checked by invoking a hello-world function I grabbed from the staging site. 
n/a
----
📚 Documentation preview 📚: https://garden-ai--590.org.readthedocs.build/en/590/
> update modal to 1.0 release

- .github/workflows/ci.yaml
- garden_ai/hpc_gardens/mlip_garden.py
- garden_ai/mcp/README.md
- garden_ai/mcp/mlip.py
- garden_ai/mcp/server.py
- tests/test_client.py
part of #596 and #591
this is a quick copy/paste of the tools from [globus-labs/science-mcps](https://github.com/globus-labs/science-mcps/tree/main/mcps/garden) that got claude to successfully submit batch relaxation on edith. 
I haven't tested this yet, because I do not currently have an allocation on edith 
----
📚 Documentation preview 📚: https://garden-ai--597.org.readthedocs.build/en/597/
> naively include tools from mlip demo

- garden_ai/mcp/server.py
#596 
This PR adds three mcp tools to the stdio based mcp server (search_gardens, get_garden_metadata, search_functions). These three tools allow for mcp clients like Claude to search through gardens based on different query parameters. The search garden functionality is split up into two tools to avoid size limit issues I was seeing when Claude would pull all the metadata for a garden(s) all at once. The normal flow for this would be user asks Claude for garden based on some parameters -> search_gardens -> user wants to know more about garden that was found/what functions available -> get_garden_metadata/search_functions
Tested manually with Claude
----
📚 Documentation preview 📚: https://garden-ai--598.org.readthedocs.build/en/598/
> MCP search/summarize functionality

- garden_ai/mcp/README.md
- garden_ai/mcp/server.py
This is a first pass at one of the two ways we're thinking about enabling function invocation.
**The problem**: An LLM is only able to send str arguments to a tool, which makes it tricky for the LLM to invoke a function that expects e.g. an `Atoms` object or a `dict`. 
Two approaches to the problem:
- (less clever) only worry about functions which accept plain str data (or dicts we read with `json.loads`). When attempting to invoke e.g. functions needing `Atoms`, just respond with a helpful error message
- (more "clever") have the LLM generate "preprocessing code" for the str data and `exec` it to build the complex argument types the function expects
This is the less clever approach. If we can get the code generation tool to reliably come up with sane code we can try the second approach …
> first pass at invoke_function tool

- garden_ai/hpc_gardens/mlip_garden.py
Closes #591. This PR adds the ability to run relaxation with 5 different MLIPs (Versions of MACE, Orb, Mattersim, Sevennet, and FairChem) on demand. 
This is an MVP of the interface. I need to add optional parameters, be more specific about the exact checkpoints being used and much more. But this is a start!
----
📚 Documentation preview 📚: https://garden-ai--613.org.readthedocs.build/en/613/
> Add cloud functions to MLIP garden

- garden_ai/hpc_gardens/mlip_garden.py
Small maintenance PR. We're not including ORB and FairChem in the initial rollout, so removing from the MLIP garden.
----
📚 Documentation preview 📚: https://garden-ai--617.org.readthedocs.build/en/617/
> Remove uncallable MLIPs

- garden_ai/hpc_executors/edith_executor.py
- garden_ai/hpc_gardens/mlip_garden.py
- garden_ai/hpc_gardens/utils.py
Resolves #616 
This PR adds model initialization logic for mattersim, sevennet, and mace to the MLIPs running on Edith. Now users can pass these model names to the `batch_relax` function:
```
import garden_ai
edith_ep_id = "<edith_id>"
my_atoms  = "./path_to_atoms.xyz"
g = garden_ai.get_garden("mlip-garden")
job_id = g.batch_relax(my_atoms, model="mace", cluster_id=edith_ep_id)
job_id = g.batch_relax(my_atoms, model="sevennet", cluster_id=edith_ep_id)
job_id = g.batch_relax(my_atoms, model="mattersim", cluster_id=edith_ep_id)
```
Pulled the model initialization code from: https://github.com/Garden-AI/uploadathon/blob/main/MLIPs/mlip_garden.py
Ineeded to create a separate conda env for MACE on Edith called 'torch-sim-edith-mace'. The `EdithExecutor` handles choosing the correct conda env …
> Add mattersim, sevennet, mace to Edith MLIP garden

- garden_ai/hpc_gardens/mlip_garden.py
Part 2 of #616 -- shouldn't have closed it until now, but oh well.
This PR combines the batching and relaxation logic from https://github.com/Garden-AI/uploadathon/blob/main/MLIPs/mlip_garden.py `_perform_batch_relaxation` with the model initialization and incremental output writing in the HPC relaxation flow.
Manual testing with MatterSim, SevenNet, and MACE
----
📚 Documentation preview 📚: https://garden-ai--621.org.readthedocs.build/en/621/
> Integrate cloud relaxation logic with HPC relaxation flow

- garden_ai/hpc_gardens/mlip_garden.py
- garden_ai/hpc_gardens/utils.py
This PR puts some final touches on the batch relaxation functions running on Edith.
I bumped the batch sizes up to take better advantage of the available GPU memory.
I also added a `relaxation_options` arg to the `batch_relax` function ala this garden: https://thegardens.ai/#/garden/10.26311%2Fcexg-2349
I also added a helper to decode any base64 output we get in the remote endpoint which makes the `JobStatus` object more user friendly.
Manual testing to make sure the relaxation flow still works.
----
📚 Documentation preview 📚: https://garden-ai--625.org.readthedocs.build/en/625/
> Bump batch sizes on edith, add relaxation options
